name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  animations: ^2.0.11
  stylish_bottom_bar: ^1.1.0
  scroll_loop_auto_scroll: ^0.0.5
  image_picker: ^0.8.7+3
  flutter_animate: ^4.5.2
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  http: ^1.4.0
  provider: ^6.0.5
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  confetti: ^0.7.0
  shared_preferences: ^2.5.3

  
  
  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
